org: solanastore
app: solana-transactions-api
service: solana-store-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: /graphql
        method: post
        cors: true
    - http:
        path: /graphql
        method: get
        cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  patterns:
    - node_modules/**
